### ISSUE TITLE
Only two of the 142 images got downloaded

### ISSUE THREAD

**Issue by zenny** [belaviyo/save-images#36]
Hi,

I am trying to download all pages from https://flbook.com.cn/c/nwDYma5rF6 using this addon. But it only downloads two first images only!

Did I miss something to download all images at once? Thanks!

Cheers, and stay safe,
/z

**Comment by belaviyo** [comment]
Thanks for the report. There was a bug preventing the extension from collecting background images. Though note that even after this fix, still, the extension cannot grab all the 142 images since the page uses a JS script to load them partially. Unfortunately, there is no fix. However, you can run this extension after every few pages and then you can have all the images.
