### ISSUE TITLE
Feature request: Ability to save in a custom folder and not in a zip file

### ISSUE THREAD

**Issue by syldub69** [belaviyo/save-images#7]
2 feature requests:
- Could you give the option to save all the images in a specific folder?
- By default, all my images are zipped in a file... Each time I have to decompress them. Why not saving each file independently by default rather than zipping them?

**Comment by belaviyo** [comment]
> Could you give the option to save all the images in a specific folder?

In Chrome, you can save in a custom dir from the UI. The only limitation is that this custom dir needs to be inside the default download directory (web-extension limitation). It is also possible to download into a custom directory from the save dialog (Gallery view)

> By default, all my images are zipped in a file... Each time I have to decompress them. Why not saving each file independently by default rather than zipping them?

Browsers are not really good at handling multiple downloads. That's the reason why we switched to the ZIP format. Basically, the extension downloads all images internally and prepares the ZIP archive then ask the browser to download this locally created ZIP archive once.

**Comment by SabreCat** [comment]
+1 to this. The ZIP plus issue #9 makes the add-on no more convenient than downloading images individually, because I have to unpack and rename everything.

**Comment by p-clemo** [comment]
+1
IDK why syldub69 used bullets, this is basically one request. (first of the two answers may be irrelevant)
Anyway. I also think that this (creating zip) is an unnecessary step. which decreases the comfort of an otherwise perfectly-working extension/addon, no matter how easily I can unzip multiple archives at once into respectively named subfolders.
Also I wonder if the zipping is done locally or somewhere outside. When your server goes offline, service would be unavailable...? Multiple downloads problem, couldn't it be solved by some sort of queue?
P.S. I think this request and #6 are duplicates.

**Comment by syldub69** [comment]
> IDK why syldub69 used bullets, this is basically one request. 

There is 2 aspects: 
- Where the download is stored (currently in a specific folder named after the domain name of the website)
- The format of the downloaded image (currently in a zip file)

> P.S. I think this request and #6 are duplicates.

You're right!

**Comment by p-clemo** [comment]
Ok. I still wonder where does the zipping take place

**Comment by atErik** [comment]
Hi, i would like to request a gzip / gz option to save images, instead of using ZIP, along with the option to use a SUB-directory (inside the "Download" or "Downloads" folder, which is less-checked or relaxed by some OSes).  
Most web-servers/websites by-default delivers gzipped content into web-browsers (web-clients). So i think gzip file would be easier & faster.  
There are some 3rd-party software, and also sometime OS's own file-browser can also mount `"*.gz"` files automatically as a folder, allows to work with files inside gzip w/o need to decompress all files.  
Support for both ZIP & gzip should exist, as some OS/platform (like: Windows/PC) prefers+supports `ZIP` & can de/compress it by itself , and some OS/platform (like: *nix, GNU/Linux, macOS/Mac, etc) prefers `gzip` & can de/compress it by itself.  
As far as i understand, ZIP related source-code are now in public-domain or can be used w/o paying royalty-fee, etc, So most major OS (file-browser) now also supports ZIP : Windows, macOS, *BSD Unix, & GNU/Linux based OS like these: Debian/Ubuntu, Fedora/RedHat, etc.
